### ISSUE TITLE
Race Condition: VyOS-CloudInit Runs Before Network Is Fully Up

### ISSUE THREAD

**Issue by byronmccollum** [higebu/vyos-cloudinit#5]
VyOS-CloudInit seems to sometimes run before the network is fully up. This results is sporadic errors attempting to communicate with the metadata service.

After the first reboot, things seem to sort themselves out, and VyOS-CloudInit is able to fetch both the user-data and the ssh-key from the metadata service.

I think a retry mechanism is needed, like the real CloudInit. Thoughts?

I should also note, this is a VyOS instance running on OpenStack, created from an ISO install. I am going though the process getting VyOS working on OpenStack, and behaving as one would expect. This includes documenting how to create an OpenStack ready image, starting from an ISO install, adding the VyOS-CloudInit deb, configuring static routes to the metadata service, and finally, exporting a nicely compressed qcow2 image.

**Comment by higebu** [comment]
Thank you for your comment.

I agree with some retry mechanism.

Documents for OpenStack are very welcome. Because I'm not familiar with OpenStack very much. I made Packer template for OpenStack: https://github.com/higebu/packer-templates/blob/master/VyOS-1.1.7-amd64/openstack.json. I wish it helps you.
